### ISSUE TITLE
Protect Header of docx file using DOCX4J

### ISSUE THREAD

**Issue by ayushgupta31** [plutext/docx4j#214]
Hi,

Does anyone have an idea how can we use DOCX4J APIs to protect the Header Part in a docx file?
Protecting the whole document is easy, but I am specifically looking to protect just the header part.
Body should be editable to the user.

Ayush

**Comment by plutext** [comment]
You can put your header content in a content control, and set it to locked so that it can't be edited or deleted.  But this is imperfect.  A user can insert sibling content next to your content control.  Or they can delete your header, or insert other headers (eg first page, odd/even, or an entirely new section).

If you can figure out a better way to do it in Word, then it ought to be simple enough to do it in docx4j.  But please use StackOverflow or the docx4j forums if you need help, since this isn't an issue as such.
