### ISSUE TITLE
.doc support

### ISSUE THREAD

**Issue by sachinmstack** [plutext/docx4j#243]
Up to the version 3.2.2 .doc conversion to pdf was supported by the class Doc. Now it seems to be removed in newer versions. I would like to know how we can convert documents in .doc format to PDF using docx4j.

**Comment by plutext** [comment]
That class was pretty simple; it was removed because it only supported basic doc to docx features, and required POI as a dependency.  You could add it back in again to your code easily enough.

You'll get better results though if you use Plutext's commercial PDF Converter, which can convert binary doc directly to PDF.

**Comment by sachinmstack** [comment]
Ok. Thank you
