### ISSUE TITLE
How to read doc or docx file with auto number?

### ISSUE THREAD

**Issue by lamdongnd** [plutext/docx4j#352]
How to read doc or docx file with auto number?
Example: 
1. 2. ...
I. II. ...
or 
=>, *.  ....

**Comment by plutext** [comment]
PDF and HTML output interpret this, using the code in https://github.com/plutext/docx4j/tree/master/src/main/java/org/docx4j/model/listnumbering

Its a bit messy I'm afraid, since it ports/integrates some Microsoft code, without refactoring for cleaner integration.

Please don't use this issue tracker for quesitons.  For questions, please use our forum or stack overflow.   So I'm closing this.
