### ISSUE TITLE
Incompatibilities with MSWord 16.0+

### ISSUE THREAD

**Issue by jasonisgraham** [plutext/docx4j#395]
After an April 14th MSWord update, certain XML namespaces are missing from the `<w:document>` when the docx file is mutated.  

Because of this Word will insist on opening the docx in compatibility mode and issue the following popups:

![msword1](https://user-images.githubusercontent.com/3493406/79886066-1f4b1900-83c6-11ea-8930-ea65b8d84e02.png)

![msword2](https://user-images.githubusercontent.com/3493406/79885996-fdea2d00-83c5-11ea-8fac-5b92a3156538.png)

This can be reproduced easily by invoking (eg) `MainDocumentPart/getJAXBNodesViaXpath()`, `MainDocumentPart/getXML()`, etc, then saving the WMLPackage.

As a workaround, we've added the following to `NamespacePrefixMappings/getNamespaceURI`:
```
if (prefix.equals("w16")) return "http://schemas.microsoft.com/office/word/2018/wordml";
if (prefix.equals("w16cex")) return "http://schemas.microsoft.com/office/word/2018/wordml/cex";
```

**Comment by jasonisgraham** [comment]
Sorry for all the commit messages.  There were lots of force pushes to address whitespace changes.  

Anyway, I followed the pattern used in https://github.com/plutext/docx4j/issues/389 ...

**Comment by plumpNation** [comment]
Just adding the error in plain text for the search engines. Thanks so much for fixing this.

> Word found unreadable content .... Do you want to recover the contents of this document ...

**Comment by plutext** [comment]
Hi Jason,

This issue was fixed previously by https://github.com/plutext/docx4j/commit/9b0731d8a2fabe75c12d013dd5f749bdcdad0670#diff-8074908b48f271665d556ebd6f6859a4 and present in the docx4j 8.1.5 release: https://www.docx4java.org/forums/announces/docx4j-8-1-5-released-t2894.html (there's a typo in the release announcement which says w16cid instead of w16cex).

Please let me know if I've missed something.  cheers .. Jason
