### ISSUE TITLE
Where are your documents?

### ISSUE THREAD

**Issue by z503951608** [plutext/docx4j#428]
System.getProperty("user.dir") + "/content.xlsx"

Where are your documents?

**Comment by plutext** [comment]
Sorry, I don't understand you question.  What are you asking?  Please rephrase...

**Comment by mchmielarz** [comment]
@plutext I guess it's a question about the place of xlsx documents used in sample projects. Could you provide directories where are they stored? Did you commit them to GH? For example, I'd like to see the content of `sample2.xlsx` used in [a variable replacement](https://github.com/plutext/docx4j/blob/26aaa13fe4408e72153053a10cd4d677274522d9/docx4j-samples-xlsx4j/src/main/java/org/xlsx4j/samples/VariableReplace.java#L38) since I have some issues with this.

**Comment by plutext** [comment]
xlsx samples are at https://github.com/plutext/docx4j/tree/master/docx4j-samples-xlsx4j/sample-docs but there is no sample2.xlsx.  That said, for variable replacement, there are really 2 things to consider:

1.  make sure your variables are formatted correctly:  for example ${key1}

2.  In the sample code, be sure to get the part which actually contains your variables!

		JaxbSmlPart smlPart = (JaxbSmlPart)opcPackagepkg.getParts().get(new PartName("/xl/sharedStrings.xml"));

OR, say:
		JaxbSmlPart smlPart = (JaxbSmlPart)opcPackagepkg.getParts().get(new PartName("/xl/worksheets/sheet1.xml"));

To understand the meaning of this, read up on the concept of the shared strings table.

You could of course do your replacement in both these parts, or indeed in other sheets.
